add bool function and test
BakcylProgramowania/paragon_back pull request #35
Opened 2024-01-05 23:02 UTC by ZMorosko

2024-01-07 11:20 UTC, patkaczm requested changes

2024-01-07 11:20 UTC, patkaczm commented on src/core/core.cpp
> +bool getLogin(const std::string &username, const std::string &password){
Not sure if `getLogin` is a good name, it suggest like we are acquiring a login from somewhere but it does not return a login but a `bool` which, on the other hand, suggest that the function check something. I'd change the name.

2024-01-07 11:20 UTC, patkaczm commented on src/core/core.cpp
> +  if(username == "Jan34") {
Its okey but could be simplified to `return username == "Jan34"`

2024-01-07 11:20 UTC, patkaczm commented on src/core/core.hpp
> +bool getLogin(const std::string &username, const std::string &password);
If the function will only check something, make it `const`

2024-01-07 11:20 UTC, patkaczm commented on src/api/CMakeLists.txt
> +target_include_directories(api-lib PRIVATE
we have `INCLUDE_DIR` set [here](https://github.com/BakcylProgramowania/paragon_back/blob/main/CMakeLists.txt#L12) which seems unused. I think it's better to use non relative paths in includes so maybe it'll be better to just add `${INCLUDE_DIR}` to `api-lib`

2024-01-07 11:20 UTC, patkaczm commented on src/api/controller/MyController.hpp
> +      bool loginSuccess = getLogin(json->username->c_str(), json->password->c_str());
Isn't a `json->username` a string? If so we do not need to create another cstring and then create another temporary string in `getLogin`

2024-01-07 13:35 UTC, patkaczm requested changes

2024-01-07 13:35 UTC, patkaczm commented on test/core/core_test.cpp
> +Authenticator auth;
Why it is created outside of the test?

2024-01-07 13:35 UTC, patkaczm commented on src/api/controller/MyController.hpp
> +#include "../core/core.hpp"
use non relative path

2024-01-07 13:35 UTC, patkaczm commented on src/core/core.hpp
> +class Authenticator {
Consider moving `Authenticator` class to authenticator.hpp/cpp
In case you decide to make it under another commit please make an issue out of this

2024-01-09 10:14 UTC, patkaczm requested changes

2024-01-09 10:14 UTC, patkaczm commented on Dockerfile
> +    cd /usr/local/include && \
This is very weird!

2024-01-09 10:14 UTC, patkaczm commented on src/api/CMakeLists.txt
> +target_include_directories(api-lib PRIVATE ${INCLUDE_DIR})
Could be combined with previous `target_include_directories`

2024-01-09 10:14 UTC, patkaczm commented on src/core/CMakeLists.txt
> +target_sources(core-lib PRIVATE authenticator.cpp)
Why don't add this source to the initial sources list in line 3?
Also why we are adding source which has already been added?

2024-01-09 10:14 UTC, patkaczm commented on src/core/authenticator.hpp
> +    Database database;
Shouldn't database be passed through the constructor?

2024-01-09 10:14 UTC, patkaczm commented on src/core/authenticator.hpp
> +#ifndef AUTHENTICATOR_HPP
#pragma once

2024-01-09 10:14 UTC, patkaczm commented on src/core/core.hpp
> +#ifndef CORE_HPP
#pragma once

2024-01-09 10:14 UTC, patkaczm commented on test/core/core_test.cpp
> +#include "core/core.cpp"
you MUST NOT include `*.cpp` here

2024-01-13 07:44 UTC, patkaczm approved these changes

2024-01-13 14:13 UTC, ddnowicki approved these changes

2024-01-13 14:13 UTC, merged