Adding register (#44)
BakcylProgramowania/paragon_back pull request #45
Opened 2024-01-18 13:24 UTC by KuWojtow

* add bool function and test

* add getLogin to core.hpp

* add path to core in CMakeLists.txt

* use getLogin func to communication with api

* fix issue

* some fix

* add bool function and test

* add getLogin to core.hpp

* add path to core in CMakeLists.txt

* use getLogin func to communication with api

* some fix

* fix issue

* some fix

* add connection core - db

* uppdate core test

* Update Dockerfile

* fix some issues

* fix issue

* fix string names in db

* update README.md

* formated with clang

* adding register to project

---------

2024-01-18 13:33 UTC, ddnowicki commented
duplicate of #37 to change branch repository

2024-01-18 19:41 UTC, patkaczm requested changes

2024-01-18 19:41 UTC, patkaczm commented on src/core/authenticator.cpp
> +                                 const std::string& email) const {
This one shouldn't be `const` since we are performing an action that significantly impacts code.

2024-01-22 06:55 UTC, patkaczm requested changes

2024-01-22 06:55 UTC, patkaczm commented on src/core/core.cpp
> +const std::vector<Product> getProducts(const json& jsonData) {
make `const` methods, do not return `const` data.

2024-01-23 11:03 UTC, ddnowicki approved these changes

2024-01-23 12:35 UTC, patkaczm requested changes

2024-01-23 12:35 UTC, patkaczm commented on src/core/core.cpp
> +std::vector<Product> const getProducts(const json& jsonData) {
this also is `const` data return, 
`const` method declaration looks like this:
return_type method_name (arguments) `const`;

2024-01-23 19:08 UTC, patkaczm approved these changes

2024-01-24 09:39 UTC, merged