Adding balance
BakcylProgramowania/paragon_back pull request #58
Opened 2024-02-04 19:21 UTC by KuWojtow

2024-02-05 17:49 UTC, patkaczm requested changes

2024-02-05 17:49 UTC, patkaczm commented on src/api/controller/MyController.hpp
> +  // ENDPOINT("POST", "/balance", changeBalance, BODY_STRING(String, body)){
if it's not needed, delete it

2024-02-05 17:49 UTC, patkaczm commented on src/core/accountManager.cpp
> +    : database(
It should rather get an db object instead creating a new one

2024-02-05 17:49 UTC, patkaczm commented on src/api/dto/BalanceDTOs.hpp
> +  DTO_FIELD(Float64, balance);    // Add this line
meaning less comment

2024-02-06 10:45 UTC, patkaczm approved these changes

2024-02-06 10:45 UTC, ddnowicki approved these changes

2024-02-06 10:47 UTC, merged