Update yml to work with database libs
BakcylProgramowania/paragon_back pull request #9
Opened 2023-12-15 19:21 UTC by KuWojtow

2023-12-16 17:05 UTC, patkaczm requested changes

2023-12-16 17:05 UTC, patkaczm commented on .github/workflows/c-cpp.yml
> +      - name: Build and Install mongoDB
This is basically the whole added value from this commit, please rebase onto newest main branch

2023-12-18 17:21 UTC, ddnowicki approved these changes

2023-12-18 17:25 UTC, patkaczm approved these changes

2023-12-18 17:26 UTC, merged